### PR TITLE
Add latest v1.3.15 changes

### PR DESCRIPTION
**Pull request by RUSshy**

### CODE REVIEW

**Comment by RUSshy** [comment]
Is there anyone? xD

**Comment by mdparker** [comment]
Hi, @RUSshy. All of the Derelict packages are currently in bugfix mode, meaning no updates. Though I maintain most of the Derelict packages, this one isn't mine. It's up to @p0nce to merge this.

However, I'm currently devoting some time to update [the BindBC packages](https://github.com/BindBC) (Derelict's successor). I'll take some time to port DerelictENet over as soon as I finish the other BindBC work on my list.

Are there any other Derelict packages you depend on that have not yet been ported over to BindBC?

**Comment by p0nce** [comment]
Hello @RUSshy . This is now in tag v4.2.0
Thanks

**Comment by RUSshy** [comment]
Thanks guys!

I'm already using your opengl and glfw libs already, so thanks for that!

There is only one package that i feel is missing, imgui

This one is pretty old https://code.dlang.org/packages/derelict-imgui

**Comment by p0nce** [comment]
The best way to proceed is to port it to BindBC and then maintain it yourself. :)

**Comment by RUSshy** [comment]
i'm not familiar with it, but i will give it a try

**Pull request merged**
