### PR TITLE
update enethost struct to current 1.3.13 version (changed in 1.3.12)

### PR DESCRIPTION
**Pull request by extrawurst**

### CODE REVIEW

**Comment by extrawurst** [comment]
this fixes issue #1

**Comment by p0nce** [comment]
Tag incoming

**Comment by p0nce** [comment]
Use tag v1.3.13

Note that you can do like this to support older versions that can be found in the wild: https://github.com/d-gamedev-team/gfm/blob/master/enet/gfm/enet/enet.d#L30

My loose desire with DerelictENet is to move to the next DerelictUtil which allows such multiple version support in Derelict. That would provide maximum portability.

**Comment by extrawurst** [comment]
Yeah I know, problem is this works only with new functions in the API. changes in those structs won't work.

**Comment by mdparker** [comment]
I recommend creating a new branch for the new version and bump the tag
to 2.0, since it is completely incompatible with previous versions.
Then in both branches, I would modify loadSymbols to do the following.

1) Load da_enet_linked_version first
2) Call da_enet_linked_version to make sure the version is compatible
with the enethost struct in this version of DerelictENet
3) Throw an exception if there is a version mismatch, otherwise continue loading

With that done, you should also add a big warning to the README. All
of this combined should help reduce the potential number of confused
users reporting the same issue over and over :)

I'm in the middle of a massively time-consuming project right now that
should keep me busy until mid-September, but if I can make some time
somewhere I'll try to move forward on the package-specific Derelict
docs so you can get a DerelictENet page going.

On Wed, May 6, 2015 at 4:44 AM, Stephan Dilly notifications@github.com wrote:

> Yeah I know, problem is this works only with new functions in the API.
> changes in those structs won't work.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Mike Parker

**Comment by p0nce** [comment]
I'm very busy too :)

`bump the tag to 2.0, since it is completely incompatible with previous versions.`

Perhaps more urgently, we have a bunch of:

``` json
"dependencies": {
        "derelict-util": ">=1.0.2"
}
```

out there that might break then and should be replaced by `~>`.

**Comment by extrawurst** [comment]
I always liked it when the bindings had the same Version tag as the bound library...

**Comment by p0nce** [comment]
It seems like a good idea, but it's not that practical:
- a patch version in derelict doesn't necessary correspond to a patch version in  (and it seems ENet doesn't use SemVer) so we gave up this idea in Derelict.
- Derelict can load multiple version with not much more effort, that's a nice things about dynamic loaders and should help Linux distribution.

**Pull request merged**
